### PR TITLE
Updates for Julia 0.7

### PR DESCRIPTION
**Pull request by macd**
Topic says it all.

### CODE REVIEW

**Comment by boydgreenfield** [comment]
@macd Thanks for taking the time to open this up. I have to confess I'm a bit behind on the latest state of Julia, but it looks like v0.7 is still a pre-release at the moment. Would it be possible to tweak this to support v0.6 and v0.7? If not, I realize the current code on `master` doesn't even support v0.6, so this is definitely _better_. 😄

**Comment by macd** [comment]
@boydgreenfield Thanks for the response on the PR.  Currently Julia 0.7 is in beta and there is a concerted push to move packages to that release.  The recommended approach is to _not_ support 0.6  (see here https://discourse.julialang.org/t/ann-introducing-upgradathon-fridays/12047/4)  Also, eventually all packages will have to switch to supporting the new Pkg (a.k.a. as Pkg3) module by including a Project.toml file, but that part is not wanted at the moment. Keno Fischer is doing weekly (at least) package evaluation runs on 0.7 and it is from that list of package failures that showed BloomFilters as failing.  It'd be great if you could merge the PR and get another module passing.  Thanks!

**Comment by boydgreenfield** [comment]
@macd That makes good sense. Thanks again for the PR (and update)!. Merging now. Please ping me again here (or open a PR) if you'd like me to a pin a release / do any packaging updates.

**Comment by macd** [comment]
Thanks!  Will let you know time comes to update to Pkg3.

**Pull request merged**
